env:
  global:
    - E2E_TESTING=none
    - DEEP_NO_INTERACTION=1

notifications:
  # Send notifications to Slack
  slack:
    secure: bYe8LfVdAcMXxijeIiHN0Z6dRxjDj6QbyaUK8HdMzDd/2daRs1k4tYBSXqzi4k0/eVBq8kB4Bm7QYzmpXrkrc/E7DpV714WCNErpAR4seLDDZ1z4J3s7e8YIlMb/C4YfENCYuqVNTWzr2xfDSrR7rnzE+xMSHSoPgDj2Vi79kzSYmzP4ZGAjH7Yq6qoR1BE4VJ1MxrAPdQIpMXC5OdJyGSY9C9fWKQ7KJX9quZIAVIgS0TlItAntx4XtvJTIhm/ZsTzH4edZrYOfyhosbJqMqYkk5JzYC61sVO1BnIKPWMILhh/jYxcN/hXogX+po5lhh+eDyq3M9yOY0IegLuWVfl6RWa4eYed0uVQQf13tDlkPRKKRk+Y3vC2dPZU5RSqFLX98tVvXNXDHGPCEM2UZY6gF4pYp8fdLR6g7pO87kIs16KMPhHhiS59SlWziKKMh87PvNvXzH7Xl4GAPYLuRhBEWR6AzJ+sje9dPV/mKILgqM61ccHtOZmEJkqzlvjoOsaT2Axych9jqDtMh2ACikzG/PrC+EK1qaU9t89zA0MjHekHYzkF6TZbPrRuVHdztmD/jYbupIgi+WQN74D4SrgQhuKZkQ+3wW/Hu4n6SR3LFapZPMfggYFHA1WhznL44BR0wDWVDPNzU5DUPQNJpqnJmJBTUN8mxinG2UwRwRFY=
